/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextChannelIdRouteImport } from './routes/text.$channelId'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'
import { Route as EditorDocIdRouteImport } from './routes/editor.$docId'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextChannelIdRoute = TextChannelIdRouteImport.update({
  id: '/text/$channelId',
  path: '/text/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => FoldersRoute,
} as any)
const EditorDocIdRoute = EditorDocIdRouteImport.update({
  id: '/editor/$docId',
  path: '/editor/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/folders': typeof FoldersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/prompts': typeof PromptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/voice': typeof VoiceRoute
  '/editor/$docId': typeof EditorDocIdRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/text/$channelId': typeof TextChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/folders': typeof FoldersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/prompts': typeof PromptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/voice': typeof VoiceRoute
  '/editor/$docId': typeof EditorDocIdRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/text/$channelId': typeof TextChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/folders': typeof FoldersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/prompts': typeof PromptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/voice': typeof VoiceRoute
  '/editor/$docId': typeof EditorDocIdRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/text/$channelId': typeof TextChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/folders'
    | '/forgot-password'
    | '/kanban'
    | '/login'
    | '/prompts'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/voice'
    | '/editor/$docId'
    | '/folders/$folderId'
    | '/share/$token'
    | '/text/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/folders'
    | '/forgot-password'
    | '/kanban'
    | '/login'
    | '/prompts'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/voice'
    | '/editor/$docId'
    | '/folders/$folderId'
    | '/share/$token'
    | '/text/$channelId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/folders'
    | '/forgot-password'
    | '/kanban'
    | '/login'
    | '/prompts'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/voice'
    | '/editor/$docId'
    | '/folders/$folderId'
    | '/share/$token'
    | '/text/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FoldersRoute: typeof FoldersRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  PromptsRoute: typeof PromptsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VoiceRoute: typeof VoiceRoute
  EditorDocIdRoute: typeof EditorDocIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TextChannelIdRoute: typeof TextChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text/$channelId': {
      id: '/text/$channelId'
      path: '/text/$channelId'
      fullPath: '/text/$channelId'
      preLoaderRoute: typeof TextChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof FoldersRoute
    }
    '/editor/$docId': {
      id: '/editor/$docId'
      path: '/editor/$docId'
      fullPath: '/editor/$docId'
      preLoaderRoute: typeof EditorDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FoldersRouteChildren {
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
}

const FoldersRouteChildren: FoldersRouteChildren = {
  FoldersFolderIdRoute: FoldersFolderIdRoute,
}

const FoldersRouteWithChildren =
  FoldersRoute._addFileChildren(FoldersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FoldersRoute: FoldersRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  PromptsRoute: PromptsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VoiceRoute: VoiceRoute,
  EditorDocIdRoute: EditorDocIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  TextChannelIdRoute: TextChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
